### PR TITLE
Fix psr-4 autoloading

### PR DESCRIPTION
**Pull request by MujibAzizi**
Fix the psr-4 autoloader so that it actually works.

### CODE REVIEW

**Comment by Biodiscus** [comment]
+1

**Comment by maxnet** [comment]
Perhaps better to move the files from /src/omnipay/ideal to /src instead of editing composer.json for consistency with other Omnipay packages?

**Comment by markdegrootnl** [comment]
Do you agree @MujibAzizi and @Biodiscus?

**Comment by MujibAzizi** [comment]
@markdegrootnl Yes!

**Comment by Biodiscus** [comment]
@markdegrootnl Sure thing

**Comment by markdegrootnl** [comment]
Fixed in 565e942c2d22dd160ce6101cc5743f131af54660

**Pull request closed without merging**
